name = "ikigaro-os"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./.output/public" }

[observability.logs]
enabled = true
invocation_logs = true

[vars]
NODE_ENV = "production"
